work_dir: ./work_di
model_saved_name: ./runs
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path_view1: ./data-ETH/train_view1.npy
  data_path_view2: ./data-ETH/train_view2.npy
  label_path: ./data-ETH/train_labels.npy
  testdata_path_view1: ./data-ETH/test_view1.npy
  testdata_path_view2: ./data-ETH/test_view2.npy
  testlabel_path: ./data-ETH/test_labels.npy
  debug: False

# model
model: model.DDCCANet.Model

device: [0]




